# Generated by Django 4.1.3 on 2022-11-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='Inactivo', max_length=10)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SA', 'Super Administrador'), ('GP', 'Gestor de Proyecto'), ('ES', 'Especialista'), ('UO', 'Usuario Operador')], default='UO', max_length=2)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_final', models.DateTimeField(null=True)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.estatusentidad')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(null=True)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.estatusentidad')),
                ('proyecto', models.ManyToManyField(to='api.proyecto')),
            ],
        ),
    ]
