# Generated by Django 4.1.3 on 2022-12-02 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ManyToManyField(to='api.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='EstatusEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ON', 'Activo'), ('OFF', 'Inactivo')], default='Inactivo', max_length=10)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Creado'), ('2', 'Atendido'), ('3', 'Asignado'), ('4', 'En Proceso'), ('5', 'En Espera'), ('6', 'Cancelado'), ('7', 'Reasignado'), ('8', 'Resuelto'), ('9', 'Validado')], max_length=15)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Urgente'), ('2', 'Alta'), ('3', 'Media'), ('4', 'Baja')], default='Baja', max_length=10)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_final', models.DateTimeField(null=True)),
                ('estatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estatusentidad')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SA', 'Super Administrador'), ('GP', 'Gestor de Proyecto'), ('ES', 'Especialista'), ('UO', 'Usuario Operador')], default='UO', max_length=2)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.estatusentidad')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.proyecto')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('folio', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('coordenadas', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.DateTimeField(null=True)),
                ('asignado', models.DateTimeField(null=True)),
                ('proceso', models.DateTimeField(null=True)),
                ('cancelado', models.DateTimeField(null=True)),
                ('reasignado', models.DateTimeField(null=True)),
                ('resuelto', models.DateTimeField(null=True)),
                ('validado', models.DateTimeField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.area')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.especialista')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.estatusticket')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.prioridad')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.BinaryField()),
                ('ticket', models.ManyToManyField(to='api.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='especialista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.estatusentidad'),
        ),
        migrations.AddField(
            model_name='area',
            name='proyecto',
            field=models.ManyToManyField(to='api.proyecto'),
        ),
    ]
