# Generated by Django 4.1.3 on 2022-12-06 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.especialista')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.estatusticket')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
        ),
    ]
