# Generated by Django 4.1.3 on 2022-11-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_proyecto_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='activo',
        ),
    ]
